### ISSUE TITLE
Taqo Client - Edit Schedule has null time object

### ISSUE THREAD

**Issue by BobEvans** [google/taqo-paco#151]
i3,X11,glinux v1.4.0

Opening in existing browser session.
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: NoSuchMethodError: The getter 'hour' was called on null.
Receiver: null
Tried calling: hour
#0      _ScheduleDetailPageState._buildTimeWidget.<anonymous closure> (package:taqo_client/pages/schedule_detail_page.dart:119)
<asynchronous suspension>

[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: NoSuchMethodError: The getter 'hour' was called on null.
Receiver: null
Tried calling: hour
#0      _ScheduleDetailPageState._buildTimeWidget.<anonymous closure> (package:taqo_client/pages/schedule_detail_page.dart:119)
<asynchronous suspension>

**Comment by BobEvans** [comment]
Note: This is SSH-ing into a linux box.
