### ISSUE TITLE
Make sure experiments with scheduled/triggered surveys does not cause errors in non-GUI mode

### ISSUE THREAD

**Issue by rundong08** [google/taqo-paco#165]
In a ssh environment without display/desktop, experiments should not crash the daemon or causing any errors (including data collecting errors) when a survey notification is supposed to be sent.

Possible approaches:
- If the daemon can work well without any changes, (i.e. the survey notification request is automatically ignored, etc.), then there is nothing to fix
- Detect existence of desktop/GUI environment and decide whether to trigger a survey
- Turn on/off survey based on joining via GUI or command line. This has a down side that it might not work as expected when a user having desktop is joining via command line.

**Comment by rundong08** [comment]
Currently, it will cause a server crash in an environment where no desktop environment were ever setup (including chrome remote destop).
```
Unhandled exception:
Invalid argument(s): The source must not be null
#0      int.tryParse (dart:core-patch/integers_patch.dart:107)
#1      notify (package:pal_event_server/src/daemon/linux/dbus_notifications.dart:165)
<asynchronous suspension>
#2      _notify (package:pal_event_server/src/daemon/notification_manager.dart:73)
<asynchronous suspension>
#3      showNotification (package:pal_event_server/src/daemon/notification_manager.dart:85)
<asynchronous suspension>
```

**Comment by rundong08** [comment]
Trying to manually create a notification by
```
gdbus call --session --dest org.freedesktop.Notifications --object-path /org/freedesktop/Notifications --method org.freedesktop.Notifications.Notify Taqo 0 '' title click '["default", "Other action", ""]' '{"urgency": <byte 2>}' 0
```
In an environment where no desktop environment were ever setup, this will generate error:
```
Error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files
```
We need to handle this error in ` (package:pal_event_server/src/daemon/linux/dbus_notifications.dart:165)`
