### ISSUE TITLE
macOS daemon throws exception on re-launch

### ISSUE THREAD

**Issue by BobEvans** [google/taqo-paco#86]
Restarted daemon manually to watch output.

Noticed unhandled exception:

Then daemon resumed.

Server PAL starting...
2021-08-30T17:07:29.067896Z INFO [Main]: Logging service is ready
2021-08-30T17:07:29.068968Z INFO [Main]: Server ready
2021-08-30T17:07:29.068999Z INFO [Daemon]: Starting linux daemon
2021-08-30T17:07:29.071797Z INFO [AppLogger]: Starting AppLogger
2021-08-30T17:07:29.071987Z INFO [CmdLineLogger]: Starting CmdLineLogger
2021-08-30T17:07:29.072084Z INFO [IntelliJLogger]: Starting IntelliJLogger
2021-08-30T17:07:29.076467Z INFO [SyncService]: Start syncing data...
2021-08-30T17:07:29.077244Z INFO [SyncService]: Found 0 public events and 1 private events to upload.
2021-08-30T17:07:29.077659Z INFO [DaemonAlarmManager]: _scheduleNextNotification from: 2021-08-30 10:07:29.077644
2021-08-30T17:07:29.077819Z INFO [ActionScheduleGenerator]: Next alarm is null
2021-08-30T17:07:30.092233Z INFO [SyncService]: Uploaded 1 private events.
2021-08-30T17:07:30.093425Z INFO [SyncService]: Syncing private events complete.
2021-08-30T17:07:30.093503Z INFO [SyncService]: Start syncing data...
2021-08-30T17:07:30.094402Z INFO [SyncService]: Found 0 public events and 2 private events to upload.
Unhandled exception:
Invalid argument(s)
#0      _StringBase.+ (dart:core-patch/string_patch.dart:267)
#1      macOSAppLoggerIsolate.<anonymous closure>.<anonymous closure> (package:pal_event_server/src/loggers/app_usage/macos/macos_helper.dart:33)
#2      _RootZone.runUnary (dart:async/zone.dart:1450)
#3      _FutureListener.handleValue (dart:async/future_impl.dart:143)
#4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696)
#5      Future._propagateToListeners (dart:async/future_impl.dart:725)
#6      Future._completeWithValue (dart:async/future_impl.dart:529)
#7      Future.wait.<anonymous closure> (dart:async/future.dart:414)
#8      _RootZone.runUnary (dart:async/zone.dart:1450)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:143)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696)
#11     Future._propagateToListeners (dart:async/future_impl.dart:725)
#12     Future._completeWithValue (dart:async/future_impl.dart:529)
#13     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567)
#14     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#15     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#16     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118)
#17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169)
2021-08-30T17:07:31.343336Z INFO [SyncService]: Uploaded 2 private events.
2021-08-30T17:07:31.345079Z INFO [SyncService]: Syncing private events complete.
2021-08-30T17:07:39.316481Z INFO [SyncService]: Start syncing data...
2021-08-30T17:07:39.317529Z INFO [SyncService]: Found 0 public events and 3 private events to upload.
2021-08-30T17:07:41.269406Z INFO [SyncService]: Uploaded 3 private events.
2021-08-30T17:07:41.270536Z INFO [SyncService]: Syncing private events complete.

**Comment by rundong08** [comment]
Should have been fixed by #89
